SELECT * FROM customer limit(20);

--Q1. What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) AS revenue 
FROM customer
GROUP BY gender;


--Q2. Verify if returning customers, with more than 5 previous purchases, 
--are more likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status


--Q3, What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue


--Q4. Wich customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);


--Q5. Wich are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) AS "average product rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


--Q6. Compare the average purchase amounts between standard and express shipping.
SELECT shipping_type, round(AVG(purchase_amount),2) AS "average purchase amount"
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;


--Q7. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers
SELECT subscription_status, 
COUNT(customer_id) AS total_customers,
round(AVG(purchase_amount),2) AS average_purchase_amount, 
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;


--Q8. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
round(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100 / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


--Q9. Group customers into: new, returning and loyal, based on their total number 
-- of previous purchases, and show the count of each group
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_group
FROM customer
)

SELECT customer_group, COUNT(*) AS num_customers
FROM customer_type
GROUP BY customer_group;


--Q10. What are the top 3 most purchased products within each category?
WITH item_counts AS (
SELECT category, item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;
